name: Integração Contínua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Instala dependências
      run: mvn dependency:resolve
    
    - name: Realizar lint
      run: mvn checkstyle:check pmd:check com.github.spotbugs:spotbugs-maven-plugin:check